#!/usr/local/bin/python
# -*- coding: utf-8 -*-

# Eimantas Paspirgelis, Bioinformatika 4 kursas
# Programa is daug failu isima fermentu kelius ir suformuoja nuorodas
# Naudojimas: python EnzymeReference

import os
import re
from collections import Counter

# Nurodomas failas i kuri rasomi rezultatai
Result = open("keggResult", "w") 				
listNumber = 0
# Nurodomas aplankas kuriame yra visi html failai
path = 'test/'		
# Visi failu pavadinimai nuskaitomi i sarasa					
listing = os.listdir(path)	
# Imama po viena faila				
for infile in listing:    
    # Atidaromas failas nuskaitymui					
    fname = open(listing[listNumber],'r')	
    # Nuskaitomas visas tekstas ir istrinami naujos eilutes simboliai	
    text = ''.join([line.replace('\n', '') for line in fname.readlines()]) 
	# Suskaiciuojama kiek is viso faile yra keliu
    countPath = text.count("/kegg-bin/show_pathway")		
    x = 0
    for i in range(countPath):	
        # Sukarpomas failas pagal fermento kelio pradzia	
        FirstSplit = text.split('/kegg-bin/show_pathway')
        # Nukerpama nereikalinga galune		
        title = FirstSplit[i+1].split('"')
        # Suformuojama nuoroda		
        Result.write("http://www.kegg.jp/kegg-bin/show_pathway" + (title[0]) + '\n')
    listNumber = listNumber+1  
